#!/bin/bash
# Create simple 1x1 PNG files as placeholders

# Create 16x16 icon
echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAADUlEQVQoU2P8z8DwHwAFBQIAX8jx0gAAAABJRU5ErkJggg==" | base64 -D > icon16.png

# Create 48x48 icon
echo "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAADUlEQVRoQ+3BMQEAAADCoPVP7WsIoAAAeAMBOAABY3HBxwAAAABJRU5ErkJggg==" | base64 -D > icon48.png

# Create 128x128 icon
echo "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAADUlEQVR42u3BMQEAAADCoPVP7WsIoAAAAJ4GBEAAAWPxpO4AAAAASUVORK5CYII=" | base64 -D > icon128.png

echo "Icons created!"
